version: '3'

services:
  postgres:
    container_name: 'meetapp-dev-postgres'
    image: 'postgres:11.5-alpine'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: 'meetapp-dev-redis'
    ports:
      - '6379:6379'
    image: redis:alpine

  mongo:
    container_name: 'meetapp-dev-mongo'
    ports:
      - '27017:27017'
    image: mongo

  mailhog:
    container_name: 'meetapp-dev-mailhog'
    image: mailhog/mailhog
    ports:
      - 8025:8025

volumes:
  postgres_data:
